<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>ContactRequests.Presentation</AssemblyName>
    <RootNamespace>ContactRequests.Presentation</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="WolverineFx" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../Application/ContactRequests.Application.csproj" />
    <ProjectReference Include="../Domain/ContactRequests.Domain.csproj" />
    <ProjectReference Include="../Infrastructure/ContactRequests.Infrastructure.csproj" />
    <ProjectReference Include="../../../Common/Common.Presentation/Common.Presentation.csproj" />
  </ItemGroup>
</Project>
