<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Infrastructure\Orders.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\Common\Common.Presentation\Common.Presentation.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="WolverineFx" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
