<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>ContactRequests.Infrastructure</AssemblyName>
    <RootNamespace>ContactRequests.Infrastructure</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../Application/ContactRequests.Application.csproj" />
    <ProjectReference Include="../Domain/ContactRequests.Domain.csproj" />
    <ProjectReference Include="../../../Common/Common.Infrastructure/Common.Infrastructure.csproj" />
  </ItemGroup>
</Project>
